export const SIGN_IN_SUCCESS_MSG = 'SIGN_IN_SUCCESS_MSG';
export const SIGN_IN_FAILURE_MSG = 'SIGN_IN_FAILURE_MSG';
export const SIGN_UP_SUCCESS_MSG = 'SIGN_UP_SUCCESS_MSG';
export const SIGN_UP_FAILURE_MSG = 'SIGN_UP_FAILURE_MSG';
export const SIGN_OUT_SUCCESS_MSG = 'SIGN_OUT_SUCCESS_MSG';
export const SIGN_OUT_FAILURE_MSG = 'SIGN_OUT_FAILURE_MSG';

export const ORDER_PLACED_SUCCESS_MSG = 'ORDER_PLACED_SUCCESS_MSG';
export const ORDER_PLACED_FAILURE_MSG = 'ORDER_PLACED_FAILURE_MSG';

export const ADD_NOTICE = 'ADD_NOTICE';
export const REMOVE_NOTICE = 'REMOVE_NOTICE';
