export const SET_ORDERS_FROM_FIREBASE = 'SET_ORDERS_FROM_FIREBASE';
export const ORDER_PLACED_START = 'ORDER_PLACED_START';
export const ORDER_PLACED_SUCCESS = 'ORDER_PLACED_SUCCESS';
export const ORDER_PLACED_FAILURE = 'ORDER_PLACED_FAILURE';